version: "3.7"
services:

## --------------------------- ORION --------------------------- ##

  woofedcrm_web_orion:
    image: douglara/woofedcrm:latest ## ---> Troque para a versão que deseja usar <--- ##
    command: bundle exec rails s -p 3000 -b 0.0.0.0

    volumes:
      - woofedcrm_public:/app/public/assets
      
    networks:
      - NOME_DA_REDE ## ---> Defina o nome da rede interna  <--- ##
      
    environment:
      ## Url WoofedCRM
      - FRONTEND_URL=https://crm.dominio.com ## Troque pelo seu dominio
      - SECRET_KEY_BASE=BDYcdCHe7luXMBgSpUVQD3mbrUbDJmGv ## Troque por uma hash de 32 caracteres

      ## Idioma
      - LANGUAGE=pt-BR

      ## Permitir/Bloquear novas Inscrições
      - ENABLE_USER_SIGNUP=true

      ## Credenciais Motor
      - MOTOR_AUTH_USERNAME=admin ## ---> Usuario para o motor <--- ##
      - MOTOR_AUTH_PASSWORD=@admin123_ ## ---> Senha para o motor <--- ##

      ## Dados Evolution API
      ## Descomente as linhas abaixo (removendo o # do inicio) para usar a Evolution API no WoofedCRM
      #- EVOLUTION_API_ENDPOINT=https://evolution.dominio.com ## Dominio da sua Evolution API
      #- EVOLUTION_API_ENDPOINT_TOKEN=a37f14b87e32f3db4a10e15a0008034f ## Sua Global Api Key da Evolution API

      ## Timezone
      - DEFAULT_TIMEZONE=Brasilia

      ## Dados OpenAI
      ## Descomente a linha abaixo (removendo o # do inicio) para usar a OpenAI no WoofedCRM
      #- OPENAI_API_KEY= 

      ## Dados PgVector
      ## Necessario ter instalado o pgvecotr e criado uma database com nome de "woofrdcrm"
      - DATABASE_URL=postgres://postgres:senha_pgvector@pgvector:5432/woofedcrm ## Troque a "senha_pgvector"

      ## Dados Redis
      - REDIS_URL=redis://redis:6379/0

      ## Dados Storage
      - ACTIVE_STORAGE_SERVICE=local

      ## Modo de Produção
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_LEVEL=debug

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.woofedcrm.rule=Host(`URL_DO_WOOFED`) ## ---> Url para o WoofedCRM <--- ##
        - traefik.http.routers.woofedcrm.entrypoints=websecure
        - traefik.http.routers.woofedcrm.tls.certresolver=letsencryptresolver
        - traefik.http.routers.woofedcrm.priority=1
        - traefik.http.routers.woofedcrm.service=woofedcrm
        - traefik.http.services.woofedcrm.loadbalancer.server.port=3000 
        - traefik.http.services.woofedcrm.loadbalancer.passhostheader=true 
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.woofedcrm.middlewares=sslheader@docker

## --------------------------- ORION --------------------------- ##

  woofedcrm_sidekiq_orion:
    image: douglara/woofedcrm:VERSAO ## ---> Troque para a versão que deseja usar <--- ##
    command: bundle exec sidekiq -C config/sidekiq.yml
   
    volumes:
      - woofedcrm_public:/app/public/assets
      
    networks:
      - NOME_DA_REDE ## ---> Defina o nome da rede interna  <--- ##
      
    environment:
      ## Url WoofedCRM
      - FRONTEND_URL=https://crm.dominio.com ## Troque pelo seu dominio
      - SECRET_KEY_BASE=BDYcdCHe7luXMBgSpUVQD3mbrUbDJmGv ## Troque por uma hash de 32 caracteres

      ## Idioma
      - LANGUAGE=pt-BR

      ## Permitir/Bloquear novas Inscrições
      - ENABLE_USER_SIGNUP=true

      ## Credenciais Motor
      - MOTOR_AUTH_USERNAME=admin ## ---> Usuario para o motor <--- ##
      - MOTOR_AUTH_PASSWORD=@admin123_ ## ---> Senha para o motor <--- ##

      ## Dados Evolution API
      ## Descomente as linhas abaixo (removendo o # do inicio) para usar a Evolution API no WoofedCRM
      #- EVOLUTION_API_ENDPOINT=https://evolution.dominio.com ## Dominio da sua Evolution API
      #- EVOLUTION_API_ENDPOINT_TOKEN=a37f14b87e32f3db4a10e15a0008034f ## Sua Global Api Key da Evolution API

      ## Timezone
      - DEFAULT_TIMEZONE=Brasilia

      ## Dados OpenAI
      ## Descomente a linha abaixo (removendo o # do inicio) para usar a OpenAI no WoofedCRM
      #- OPENAI_API_KEY=

      ## Dados PgVector
      ## Necessario ter instalado o pgvecotr e criado uma database com nome de "woofrdcrm"
      - DATABASE_URL=postgres://postgres:senha_pgvector@pgvector:5432/woofedcrm ## Troque a "senha_pgvector"

      ## Dados Redis
      - REDIS_URL=redis://redis:6379/0

      ## Dados Storage
      - ACTIVE_STORAGE_SERVICE=local

      ## Modo de Produção
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_LEVEL=debug
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
          
## --------------------------- ORION --------------------------- ##

  woofedcrm_job_orion:
    image: douglara/woofedcrm:VERSAO ## ---> Troque para a versão que deseja usar <--- ##
    command: bundle exec good_job
    
    volumes:
      - woofedcrm_public:/app/public/assets
      
    networks:
      - NOME_DA_REDE ## ---> Defina o nome da rede interna  <--- ##
      
    environment:
      ## Url WoofedCRM
      - FRONTEND_URL=https://crm.dominio.com ## Troque pelo seu dominio
      - SECRET_KEY_BASE=BDYcdCHe7luXMBgSpUVQD3mbrUbDJmGv ## Troque por uma hash de 32 caracteres

      ## Idioma
      - LANGUAGE=pt-BR

      ## Permitir/Bloquear novas Inscrições
      - ENABLE_USER_SIGNUP=true

      ## Credenciais Motor
      - MOTOR_AUTH_USERNAME=admin ## ---> Usuario para o motor <--- ##
      - MOTOR_AUTH_PASSWORD=@admin123_ ## ---> Senha para o motor <--- ##

      ## Dados Evolution API
      ## Descomente as linhas abaixo (removendo o # do inicio) para usar a Evolution API no WoofedCRM
      #- EVOLUTION_API_ENDPOINT=https://evolution.dominio.com ## Dominio da sua Evolution API
      #- EVOLUTION_API_ENDPOINT_TOKEN=a37f14b87e32f3db4a10e15a0008034f ## Sua Global Api Key da Evolution API

      ## Timezone
      - DEFAULT_TIMEZONE=Brasilia

      ## Dados OpenAI
      ## Descomente a linha abaixo (removendo o # do inicio) para usar a OpenAI no WoofedCRM
      #- OPENAI_API_KEY=

      ## Dados PgVector
      ## Necessario ter instalado o pgvecotr e criado uma database com nome de "woofrdcrm"
      - DATABASE_URL=postgres://postgres:senha_pgvector@pgvector:5432/woofedcrm ## Troque a "senha_pgvector"

      ## Dados Redis
      - REDIS_URL=redis://redis:6379/0

      ## Dados Storage
      - ACTIVE_STORAGE_SERVICE=local

      ## Modo de Produção
      - RAILS_ENV=production
      - RACK_ENV=production
      - NODE_ENV=production
      - RAILS_LOG_LEVEL=debug
      
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
          
## --------------------------- ORION --------------------------- ##

volumes:
  woofedcrm_public:
    external: true
    name: woofedcrm_public

networks:
  NOME_DA_REDE: ## ---> Defina o nome da rede interna  <--- ##
    external: true
    name: NOME_DA_REDE ## ---> Defina o nome da rede interna  <--- ##